
# status
STATUS_SLEEP = 'slp'
STATUS_POISON = 'psn'
STATUS_PARALYSIS = 'par'
STATUS_TOXIC = 'tox'
STATUS_BURN = 'brn'

STATUS_VALUE_MULTIPLIERS = {
    STATUS_SLEEP: 2,
    STATUS_POISON: 1.1,
    STATUS_PARALYSIS: 1.5,
    STATUS_TOXIC: 1.2,
    STATUS_BURN: 1.5,
}

SPEED_CONTROL_MOVES = {
    "tailwind": 3,
    "icywind": 1.75,
    "electroweb": 2,
    "bulldoze": 0.75,
    "cottonspore": 1.25,
    "drumbeating": 1.25,
    "glaciate": 1.25,
    "lowsweep": 1,
    "rocktomb": 1.25,
    "scaryface": 0.5,
    "stickyweb": 3,
    "stringshot": 1.5,
    "syrupbomb": 1.25,
    "tarshot": 1.25,
    "toxicthread": 1.25,
    "venomdrench": 1.25,
    "thunderwave": 1.5,
    "nuzzle": 1.25,
    "glare": 1.75,
}

# move target types
SINGLE_TARGET_MOVES = {"normal", "any", "adjacentallyorself",}
HITS_PARTNER_MOVES = {"alladjacent"}
TARGET_ALLYS = {"adjacentally", "allySide"}
SPREAD_MOVES = {"alladjacentfoes","foeside"}
MOVES_WEIGHT_BY_NAME: dict[str,float] = {
    'encore': 1.25,
    'disable': 1.25,
    'yawn': STATUS_VALUE_MULTIPLIERS[STATUS_SLEEP],
    'taunt': 1.5,
    'reflect': 1.5,
    'lightscreen': 1.5,
    'helpinghand': 2,
    'wideguard': 2,
    'healbell': 0.05,
    'aromatherapy': 0.05,
    'refresh': 0.05,
    'aromatherapy': 0.05,
    'recover': 0.25,
    'roost': 0.25,
    'slackoff': 0.25,
    'softboiled': 0.25,
    'milkdrink': 0.25,
    'healorder': 0.25,
    'shoreup': 0.25,
    'moonlight': 0.05,
    'morningsun': 0.05,
    'synthesis': 0.05,
    'wish': 0.05,
    'lifedew': 1,
    'healpulse': 1,
    'floralhealing': 1,
    'strengthsap': 1,
    'leechseed': 0.75,
    'defog': 0.5,
    'substitute': 0.5,
    
}

PROTECT_LIKE = {
    'protect': 1,
    'detect': 1,
    'spikyshield': 2,
    'burningbulwark': 2,
    'kingsshield': 2,
    'silktrap': 2,
    'banefulbunker': 2,
    'obstruct': 2,
}


BAD_MOVES_SET = {
    # TODO I don't think these belong here but might need specific code to implement their value
    "naturepower",
    "secretpower",
    "speedswap",
    "skillswap",
    "allyswitch",
    "recycle",
    "sleeptalk",
    "soak",
    "imprison",
    "trick",
    "switcheroo",
    "focusenergy",
    "dragoncheer",
    "rest",
    "endure",
    "honeclaws",
    "batonpass",
    "stealthrock",
    "spikes",
    'aquaring',
    'ingrain',
    'painsplit',

    # bad moves
    'purify',
    "psywave",
    "growl",
    "leer",
    "splash",
    "celebrate",
    "holdhands",
    "constrict",
    "synchronoise",
    "watersport",
    "mudsport",
    "happyhour",
    # "grasswhistle",
    "present",
    # "teleport",
    "spotlight",
    "rototiller",
    "luckychant",
    "miracleeye",
    "odorsleuth",
    "foresight",
    "embargo",
    "healblock",
    "worryseed",
    "simplebeam",
    "entrainment",
    "bestow",
    "holdback",
    "captivate",
    "magneticflux",
    "gearup",
    "iondeluge",
    "electrify",
    "magicroom",
    "wonderroom",
    "powder",
    "craftyshield",
    "quickguard",
    # "wideguard",
    # "matblock",
    "flowershield",
    "aromaticmist",
    "lunardance",
    "healingwish",
    "memento",
    # "finalgambit",
    "nightmare",
    "snore",
    "trumpcard",
    "rage",
    "bide",
    "frustration",
    "return",
    "assist",
    "mefirst",
    "mimic",
    "copycat",

    "camouflage",
    "conversion",
    "conversion2",
    "topsyturvy",
    # "psychup",
    # "guardsplit",
    # "powersplit",
    # "guardswap",
    # "powerswap",
    # "heartswap",
    "roleplay",

    "gastroacid",
    "reflecttype",
    "forestscurse",
    "trickortreat",
    "refresh",
    "purify",
    "grudge",
    "spite",
    "eeriespell",
    "torment",
    "imprison",
    # "disable",
    "sandattack",
    "kinesis",
    "flash",
    "supersonic",
    "sweetkiss",
    # "dynamicpunch",
    # "slam",
    "eggbomb",
    # "barrage",
    # "boneclub",
    # "skullbash",
    # "razorwind",
    # "clamp",
    # "whirlpool",
    # "bind",
    # "wrap",
    # "firespin",
    # "infestation",
    # "detect",
    # "afteryou",
    "aquaring",
    "attract",
    "belch",
    "block",
    "burnup",
    "charge",
    "confide",
    "courtchange",
    # "covet",
    # "defog",
    # "destinybond",
    "doubleteam",
    # "echoedvoice",
    # "endeavor",
    # "facade",
    "fairylock",
    # "followme",
    # "furycutter",
    # "grassyterrain",
    # "guardsplit",
    # "helpinghand",
    # "howl",
    # "incinerate",
    # "ingrain",
    "laserfocus",
    "magnetrise",
    "meanlook",
    "metronome",
    "mist",
    # "mistyterrain",
    # "mudslap",
    "naturalgift",
    "payday",
    "powertrick",
    # "quash",
    # "ragepowder",
    # "round",
    "safeguard",
    "snatch",
    "stockpile",
    "swallow",
    # "tailwind",
    "teatime",
    # "tickle",

    "acupressure",
    # "autotomize",
    # "barrier",
    # "beakblast",
    # "chargebeam",
    # "chatter",
    # "coil",
    # "curse",
    # "defensecurl",
    # "dig",
    # "dive",
    # "dragoncheer",
    # "endure",
    # "flamecharge",
    # "focusenergy",
    # "frostbreath",
    # "geomancy",
    # "growth",
    # "harden",
    # "healpulse",
    # "meditate",
    # "minimize",
    # "poisongas",
    # "poisonpowder",
    "psychoshift",
    # "sharpen",
    "sketch",
    "smokescreen",
    # "solarbeam",
    # "solarblade",
    # "steamroller",
    # "substitute",
    # "sunnyday",
    # "raindance",
    # "sandstorm",
    # "hail",
    "tailwhip",
    # "toxicthread",
    "transform",
    # "venomdrench",
    "withdraw",
    "workup",
    "telekinesis",
    # "waterpulse",
    # "venoshock",
    "confuseray",
    "leer",
    "growl",
    "futuresight",
    "upperhand",
    "dreameater",
    
    
}